# Generated by Django 5.1.1 on 2024-09-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addEmployeeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageFile', models.ImageField(max_length=200, upload_to='images/')),
                ('empName', models.CharField(max_length=60)),
                ('empBirthDate', models.DateField()),
                ('empEmail', models.EmailField(max_length=254)),
                ('empNum', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
